language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install

script:
  - pep8 storjnode
  - pep8 examples
  - pep8 tests
  - coverage run --source="storjnode" -m unittest --quiet tests

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
