language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq graphviz

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install

script:
  - coverage run --source="storjnode" -m unittest --quiet tests

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
